spring.application.name=notification-service

server.port=0

eureka.client.service-url.defaultZone=http://eureka:password@discovery-server:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.instance.prefer-ip-address=true

#actuator
management.endpoints.web.exposure.include=health

spring.threads.virtual.enabled=true
#Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-service
spring.kafka.consumer.group.audit=notification-audit-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

#Keycloak
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8181/realms/microserviceha-realm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8181/realms/microserviceha-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8181/realms/microserviceha-realm/protocol/openid-connect/certs


# Número máximo de intentos (el primero + 2 reintentos)
resilience4j.retry.instances.notification-service.max-attempts=3
# Tiempo de espera inicial entre reintentos
resilience4j.retry.instances.notification-service.wait-duration=2s
# Multiplicador para que cada espera sea más larga (2s -> 4s -> 8s)
resilience4j.retry.instances.notification-service.enable-exponential-backoff=true
resilience4j.retry.instances.notification-service.exponential-backoff-multiplier=2
resilience4j.retry.instances.notification-service.exponential-max-wait-duration=10s

# Si el proceso tarda más de 3s, se cancela y se considera error
resilience4j.timelimiter.instances.notification-service.timeout-duration=3s
resilience4j.timelimiter.instances.notification-service.cancel-running-future=true

